### ISSUE TITLE
Add ritlug-root to the GitHub org

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/infrastructure#24]
`ritlug-root` is used for GitLab (inc. CI) on the RITlug side. I'd like to test deploying the fossrit website via GitLab Pages. To do this I need `ritlug-root` added to the org

**Comment by ct-martin** [comment]
As a note, this is to test the plausibility and does not need to actually be used

**Comment by ritjoe** [comment]
This is on the RITLUG-hosted Gitlab instance, right?

**Comment by jwflory** [comment]
The account is added. Closing as complete! :clapper:
