### ISSUE TITLE
Write an Ansible playbook for Discourse

### ISSUE THREAD

**Issue by nlMeminger** [FOSSRIT/infrastructure#34]
# Summary

Create an Ansible playbook for DIscourse

# Background

We want to make discourse easy to maintain, so we want to automate this

# Details

Write a playbook in Ansible to control the deployment of Discourse and the configuration of it, then test in a vagrant VM before moving onto production deployment.

# Outcome

We have a discourse site to use for FOSS classes that is easy to deploy and maintain

**Comment by jwflory** [comment]
Domain acquired. Working on this today.

**Comment by jwflory** [comment]
Installed and configured, but hit a snag with HTTPS / LetsEncrypt in the provided container. Will revisit again soon. Also, seems like Ansible won't be necessary after all because of the Docker installation guide.

**Comment by jwflory** [comment]
The Discourse site is now online at [fossrit.community](https://fossrit.community/). No Ansible playbook is necessary because of how the Docker installation method works. I'm going to close this issue as complete. :clapper:
