### ISSUE TITLE
Service disruption: Slack bridge gone one-way

### ISSUE THREAD

**Issue by Tjzabel** [FOSSRIT/infrastructure#35]
# Summary
Slack messages are not currently going over to IRC side, but I can see IRC messages. 
@jwflory was saying this is possibly due to his slack account privileges being downgraded, and since the slack bot is based off his account, it does not have the correct privileges any more. 

# Expected results
IRC <--> Slack 

1. Send message on IRC, shows up on slack
2. Send message on slack, shows up on IRC

# Actual results
Messages from slack do not show up in IRC chat

1. Send message on IRC, it shows up in slack
2. Send message on slack, it does not show up in IRC

# Priority requested

* **Urgency**: high

**Comment by jwflory** [comment]
> Send message on slack, it does not show up in IRC

I misunderstood. This issue is likely an IRC channel problem (I originally thought IRC messages weren't appearing in Slack). I will debug on Friday.

**Comment by jwflory** [comment]
It seems like this is resolved. Maybe the bot temporarily lost voice in the IRC channel. If it happens again, please reopen the issue and I'll take a look.
