### ISSUE TITLE
Change command prefix on fanshawe

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/infrastructure#37]
# Summary

Change the prefix that fanshawe uses for commands to something other than `.`

# Background

Fanshawe sees any message that starts with `.` as a command and then tries to parse it. However, messages are often started with `...`, which fanshawe will attempt to parse and then drop an error message in chat, which is annoying.

# Details

Configuration change

# Outcome

See Summary

**Comment by jwflory** [comment]
Implemented in jwflory/infrastructure@bb4b8f3447950e5ba70bbaa2c39e56e69978259c. @ct-martin Thanks for opening a ticket on this.
