### ISSUE TITLE
Bridge RITlug #projects to freenode

### ISSUE THREAD

**Issue by Tjzabel** [FOSSRIT/infrastructure#41]
Currently, most RITlug slack channels are available on freenode. One withstanding channel is `#projects`. This would enable even further contributions from those on either side of the bridge.

This is related to [this](https://github.com/RITlug/infrastructure/issues/15) RITlug Infrastructure issue.

**Comment by jwflory** [comment]
@Tjzabel Could you please register an IRC channel first? You can use [these guidelines](https://docs.pagure.org/infra-docs/sysadmin-guide/sops/freenode-irc-channel.html). Let me know what IRC channel to bridge to, and I'll get this sometime this week.

Also, note that the channel should be prefixed to our registered group namespace on Freenode, `#rit-*`.

**Comment by Tjzabel** [comment]
@jwflory done! `#rit-lug-projects` has been created :+1: 

Let me know if I need to do anything else.

**Comment by jwflory** [comment]
This was fixed in commit 4eeb188aca9f5e5e6cdd32cd567f089d8c648dae. This change is currently running in production and the channels are now bridged.
