### ISSUE TITLE
Service disruption: Slack bot died

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/infrastructure#42]
# Summary

bridge to slack has stopped working. No messages going either way

# Expected results

Messages bring bridges both ways on relevant channels

# Actual results

messages not being sent to either side, unknown if bot errored or died

# Priority requested

* **Urgency**: high/medium
* **Requested deadline**: reasonably soon

# Other details

Can we get auto-restarts, monitoring, or something for the bot?

**Comment by jwflory** [comment]
Thanks for your patience on this one. I wanted to debug why this happened and try to automate a fix when it does. Unfortunately, when I logged on, the service was still running and logs were empty. I restarted the service manually and confirmed the bridge is back online.

Closing this as fixed. :clapper: In the future, if it happens again, please open a new ticket and I should be able to jump on this faster if it is a problem I can't automate a fix for right now.
