### ISSUE TITLE
Service disruption: Slack bridge down

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/infrastructure#45]
Summary

bridge to slack has stopped working. No messages going either way
Expected results

Messages bring bridges both ways on relevant channels
Actual results

messages not being sent to either side, unknown if bot errored or died
Priority requested

    Urgency: high/medium
    Requested deadline: reasonably soon

Other details

Can we get auto-restarts, monitoring, or something for the bot?

**Comment by jwflory** [comment]
As with #42, a restart fixed it again. This time I had logs though:

```
-- Logs begin at Tue 2019-04-09 16:59:40 EDT, end at Fri 2019-04-12 10:47:26 EDT. --
Apr 11 11:24:33 ritlug-irc matterbridge[11525]: time="2019-04-11T11:24:33-04:00" level=error msg="Not connected to server, dropping message" prefix=irc
Apr 11 20:43:42 ritlug-irc matterbridge[11525]: time="2019-04-11T20:43:42-04:00" level=error msg="Not connected to server, dropping message" prefix=irc
Apr 12 10:23:53 ritlug-irc matterbridge[11525]: time="2019-04-12T10:23:53-04:00" level=error msg="Not connected to server, dropping message" prefix=irc
```

It's not clear to me why Matterbridge does not try to auto-reconnect. I'll try to chase this one back upstream.
