### ISSUE TITLE
Move #rit-foss back to latest TeleIRC release once new release is tagged

### ISSUE THREAD

**Issue by Tjzabel** [FOSSRIT/infrastructure#53]
`#rit-foss` is currently being used as another testing bed for TeleIRC, running off HEAD for the remainder of these summer days. However, since this channel is used for classroom communications, we should move it back to the latest stable `{{ default_version }}` once the next release is out.

**Comment by Tjzabel** [comment]
@jwflory since we don't currently have plans to cut a release soon, should we simply move `#rit-foss` back to the latest release since the semester has started?

I haven't looked into what changes we've made since the last release, but I think we should either cut a minor release with what we have (html escaping and other fixes), or just revert this channel back.

**Comment by jwflory** [comment]
@Tjzabel I'm in favor of cutting a new release and distributing this version more widely on the services we maintain. Will you be at FOSS Hours this coming Thursday?

**Comment by Tjzabel** [comment]
@jwflory Yes, I will be at FOSS Hours this Thursday.

**Comment by jwflory** [comment]
@Tjzabel Awesome – if we can grab 30 minutes there, I can run you through the release process I am following and we can push a new TeleIRC release out.

**Comment by Tjzabel** [comment]
Sounds good :+1:

**Comment by jwflory** [comment]
This was done last night! See FOSSRIT/infrastructure#55. Closing as complete.
