### ISSUE TITLE
Fix Telegraf on irc-lug

### ISSUE THREAD

**Issue by Tjzabel** [FOSSRIT/infrastructure#54]
The telegraf monitoring service is currently installed and running on the `irc-lug` server, but is failing to run due to misconfiguration.

This should either be removed, or set up correctly so we have effective monitoring.

**Comment by jwflory** [comment]
@Tjzabel The InfluxDB back-end is disconnected. There is not an easy fix for this task; now is a good opportunity to investigate a more sustainable monitoring solution.

**Comment by jwflory** [comment]
I stopped and disabled the `telegraf.service` file on the host. This is something that would be nice to have, but I don't see a sustainable way of setting this up and documenting it before I depart from RIT officially in the next couple of weeks.

Closing as `wontfix`. :european_post_office:

**Comment by Tjzabel** [comment]
@jwflory sounds good to me :+1: 

Thanks for looking at the issue.
