### ISSUE TITLE
github.com/ritjoe deprecated

### ISSUE THREAD

**Issue by deejoe** [FOSSRIT/infrastructure#87]
Please be advised that https://github.com/FOSSRIT/hfoss exists. I have been inconsistent with merging ritjoe/hfoss back into the master branch of this repository but have done so at least once, 3 years ago. 

More recently, I created the branch https://github.com/FOSSRIT/hfoss/tree/2015F-2020S as being up to date with what I had in ritjoe/hfoss at the end of the Spring 2020 semester (RIT term 2195 as per https://www.rit.edu/calendar/1920). I know of no reason this couldn't be merged into the FOSSRIT/hfoss master branch but I figured this was a cleaner, more obvious waypoint. 

The third branch in FOSSRIT/hfoss (develop) I'll address in a different issue.

I saw some links in a document associated with the instance of HFOSS that started today (Spring 2021, RIT term 2205) pointing back to ritjoe/hfoss that would probably be better directed to one of the branches of FOSSRIT/hfoss 

@Nolski @jwflory @whenbellstoll @itprofjacobs

**Comment by deejoe** [comment]
I titled this issue (#87) "github.com/ritjoe deprecated" but I did not make it so clear in the body of that first message that I am retiring the ritjoe github account.

I figured I'd let this past semester (Spring 2021, RIT Term ID 2205) play out before making any potentially-breaking changes. 

Now that the semester is in the can, I'm looking again to move forward with this.

**Comment by ritjoe** [comment]
> I titled this issue (#87) "github.com/ritjoe deprecated" but I did not make it so clear in the body of that first message that I am retiring the ritjoe github account.

And I'm commenting from the @ritjoe account in question, to cross-validate the basic premise of this plan.

**Comment by ritjoe** [comment]
Since ritjoe/ritjoe was meant to be the metarepository for @ritjoe I may put more of the moment-by-moment chatter about this process there, in ritjoe/ritjoe#1

that content will not survive within Github past the removal of @ritjoe but can still live on in, for example, email notifications.

**Comment by ritjoe** [comment]
Over a year since opening this issue. Am going to get around to deleting this all Real Soon Now.

**Comment by jwflory** [comment]
I think the added [`2015F-2020S` branch](https://github.com/FOSSRIT/hfoss/tree/2015F-2020S) is enough to allay concerns. I imagine @itprofjacobs updated the HFOSS syllabus by now to point towards other places. I'll close this issue because I think all historical work from 2015 to 2020 is already preserved in the FOSSRIT/hfoss repo, so no further action is needed.

Thanks for helping keep this history preserved @deejoe!
